### ISSUE TITLE
PPU breaking due to operator precedence

### ISSUE THREAD

**Issue by wheremyfoodat** [CocoSimone/natsukashii#1]
https://github.com/CocoSimone/natsukashii/blob/master/src/core/ppu.cpp#L330-L334

The `<< 1` instances here get preceded by the additions so tile data is not read properly.
This happens because the shift operators have lower precedence than the addition operator.

**Comment by CocoSimone** [comment]
Thanks. I'll proceed to fix this bug tomorrow. Always helpful looking into others' code :rpog:❤️

**Comment by CocoSimone** [comment]
Thanks again. This fixed my issue and I'm now able to see Nintendo's logo correctly. :heart:

**Comment by wheremyfoodat** [comment]
:rpog:
